plugins:
  - uses:
    - plugin: https://ubiquity-os-daemon-pricing-fix-label-generation.fernand-veyrier.workers.dev
      skipBotEvents: false
      with:
        labels:
          time:
            - name: "Time: <7.5 Minutes"          
            - name: "Time: <1 Hour"
            - name: "Time: <2 Hours"
            - name: "Time: <4 Hours"
            - name: "Time: <1 Day"
            - name: "Time: <1 Week"
          priority:
            - name: "Priority: 1 (Normal)"
            - name: "Priority: 2 (Medium)"
            - name: "Priority: 3 (High)"
            - name: "Priority: 4 (Urgent)"
            - name: "Priority: 5 (Emergency)"
        basePriceMultiplier: 1
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
          protectLabels:
            - price
            - time
            - priority
