plugins:
  - uses:
    - plugin: https://ubiquity-os-daemon-pricing-fix-label-generation.fernand-veyrier.workers.dev
    # - plugin: https://comic-bee-miserably.ngrok-free.app 
      skipBotEvents: false
      with:
        labels:
          time:
            - name: "Time: <7.7 Minutes"
            - name: "Time: <27.7 Minutes"
            - name: "Time: <1 Hour"            
          priority:
            - name: "Priority: 1 (Normal)"
            - name: "Priority: 2 (Medium)"
            - name: "Priority: 3 (High)"
            # - name: "Priority: 4 (Urgent)"
            # - name: "Priority: 5 (Emergency)"
        basePriceMultiplier: 100
        publicAccessControl:
          setLabel: true
          fundExternalClosedIssue: false
          protectLabels:
            - price
            - time
            - priority
        # globalConfigUpdate:
        #   excludeRepos: []
